### PR TITLE
shuttle 图标 高清重制

### PR DESCRIPTION
**Pull request by pluwen**
重新绘制，并增加 512*512 图标

### CODE REVIEW

**Comment by thshdw** [comment]
Hi @pluwen I'm curious, why did you close your pull? These icons look a bit cleaner. I have an open issue to fix the icon too see https://github.com/fitztrev/shuttle/issues/141

**Comment by pluwen** [comment]
some details is not perfect, I will fix it later, then try the pull the new one, thank you for your reply

**Comment by pluwen** [comment]
It's done
https://github.com/fitztrev/shuttle/pull/178

**Comment by thshdw** [comment]
@pluwen You're Welcome! Thank you for your contribution.

**Pull request closed without merging**
