### PR TITLE
Add Chinese Language for Menu

### PR DESCRIPTION
**Pull request by pluwen**
RT

### CODE REVIEW

**Comment by thshdw** [comment]
@pluwen This is great, thanks. I have some dialog boxes that are all in english. Could you translate those too?

**Comment by thshdw** [comment]
@pluwen you can see screen shots in the v.1.2.5 release notes https://github.com/fitztrev/shuttle/releases/tag/v1.2.5

**Comment by pluwen** [comment]
need more time

**Comment by thshdw** [comment]
No worries.. when you have time. Also the help about window too 😄

**Comment by thshdw** [comment]
Should we merge this now or should we wait till the other dialog boxes are translated?

**Comment by pluwen** [comment]
merge it now, I will translate other dialog later

**Pull request merged**
