### PR TITLE
Add more ssh_config directives #161

### PR DESCRIPTION
**Pull request by skebi69**
Instead of the following in AppDelegate.m:

```
  // if everything worked out we will see a non-nil itemList where the
    // system should be appended to. part hold the last part of the splitted string (aka hostname).
    if (itemList) {
        // build the corresponding ssh command
        NSString* cmd = [NSString stringWithFormat:@"ssh %@", key];
```

we change it to:

```
    // if everything worked out we will see a non-nil itemList where the
    // system should be appended to. part hold the last part of the splitted string (aka hostname).
    if (itemList) {      
        // build the corresponding ssh command
        NSString* cmd = servers[key][@"cmd"] ?
            cmd = servers[key][@"cmd"] : [NSString stringWithFormat:@"ssh %@", key];
```

### CODE REVIEW

**Comment by thshdw** [comment]
Thanks! I'll test this out and merge if the testing goes well.

**Comment by skebi69** [comment]
Thanks.




John Kennedy  (_8(|)
I have a yellow dog:
http://www.theyellowdogproject.com/The_Yellow_Dog_Project/About.html

Sometimes it happens, sometimes it doesn't - Pedro Catacora

Just because nobody disagrees with you doesn't mean you are correct.

Anatidaephobia is the fear that somehow, somewhere a duck is watching you -
urbandictionary.com

The Dunning-Kruger effect occurs when incompetent people not only fail to
realize their incompetence, but consider themselves much more competent
than everyone else. Basically - they're too stupid to know that they're
stupid.

**Comment by thshdw** [comment]
@skebi69 Thanks for taking the time to contribute. I'm going to close this for now due to conflicting files due to a bunch of changes. Please get the latest and do another pull.

**Comment by skebi69** [comment]
I will do that. Thanks for a great app and working with me on it...

John Kennedy  (_8(|)


Sometimes it happens, sometimes it doesn't - Pedro Catacora

“Think of how stupid the average person is, and realize half of them are
stupider than that.” - George Carlin

The Dunning-Kruger effect occurs when incompetent people not only fail to
realize their incompetence, but consider themselves much more competent
than everyone else. Basically - they're too stupid to know that they're
stupid.

**Pull request closed without merging**
