### PR TITLE
Handle situation where iTerm is running but has no windows.

### PR DESCRIPTION
**Pull request by mortonfox**
I noticed that Shuttle 1.2.5 still does not correctly handle the situation where you run a command while iTerm is running without any windows open. Although it does open a new tab, the tab shows up with the default theme and not the custom theme, if you specified one. This is a weird state that iTerm gets into that doesn't happen often in practice, although I have stumbled across it a few times already since upgrading to Shuttle 1.2.5.

To reproduce the problem:
 1. Run iTerm.
 1. Hit shift-cmd-w to close the window but do not quit iTerm.
 1. Run a command with a custom theme from the Shuttle menu. The tab shows up with the default theme instead.

The solution is to check if `current terminal` succeeds and call `make new terminal` if not. Then use that terminal to launch the session. This code was part of my previous pull request. I haven't tried it in iTerm Nightly yet, so for now, I have only modified the AppleScript for iTerm Stable.

Addendum: After reading the AppleScript for iTerm Nightly, I see it does handle the case where iTerm has no current window. So this is just for iTerm Stable.

### CODE REVIEW

**Comment by thshdw** [comment]
Hello, 
I'm aware of this issue see #143 These changes are already in my development sandbox. You can try this version here #155 its posted at the bottom.
Thanks!

**Comment by mortonfox** [comment]
I just gave the sandbox version a try but that build does not resolve the problem I'm seeing, so this may not be the same issue as #155.

**Comment by thshdw** [comment]
Thanks for reporting... I'll troubleshoot to see what is going on.

**Comment by thshdw** [comment]
Well... I have neglected to compile the applescripts for inclusion to the shuttle.app :disappointed: Sorry about that...I'll update it in a moment so you can test again.

**Comment by thshdw** [comment]
@mortonfox I have compiled the scripts could you test again for me? Binary is posted in #155 

Make sure that you keep the theme default in iTerm and you change theme your JSON settings.

**Comment by mortonfox** [comment]
No, this new sandbox version does not appear to resolve the issue I described either.

**Comment by thshdw** [comment]
Interesting. It's working for me. I open iTerm close the window but keep the app running per your instructions. Run my command and it works as expected  

Sent from Outlook Mobile




On Tue, Jan 12, 2016 at 8:04 AM -0800, "Morton Fox" <notifications@github.com> wrote:












No, this new sandbox version does not appear to resolve the issue I described either.

**Comment by thshdw** [comment]
There does not seem to be an AppleScript way to fetch the iTerm default theme. Due to this you have to keep iTerm's default theme / profile as "Default" You should use the new directives in shuttle to set a global theme and you can override that theme per command using the command level theme settings.

Use the new directives in shuttle to set a theme globally 
```"default_theme": "VALUE",```

then use the command level settings to change the theme per command. 
```"theme": "VALUE",```

**Comment by mortonfox** [comment]
My iTerm's default theme is "Default" as you specified, but the sandbox version doesn't work. What happens is on an iTerm with no current window, the first tab Shuttle opens ignores my theme setting but the next tab it opens has the correct theme.

May I see what AppleScript the sandbox version uses?

**Comment by thshdw** [comment]
@mortonfox Sure I just uploaded them
https://github.com/thshdw/shuttle/tree/sandbox/apple-scripts

This is working for me... I open iTerm press command + shift + w run my command it it opens first time as expected.

here is the JSON i'm using as my test. 
```
{
  "editor": "default",
  "launch_at_login": false,
  "terminal": "iTerm",
  "iTerm_version": "nightly",
  "default_theme": "Default",
  "open_in": "tab",
  "show_ssh_config_hosts": false,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],
  "hosts": [
    {
      "cmd": "ps aux | grep defaults",
      "theme": "Homebrew",
      "title": "test",
      "inTerminal": "tab",
      "name": "Grep - Opens in new tab"
    }
  ]
}
  
```

**Comment by mortonfox** [comment]
Oh, wait a minute. You're using iTerm nightly?

That may explain why we're not getting the same results because I'm using iTerm stable and I believe that uses a different AppleScript.

**Comment by thshdw** [comment]
I'll check the stable settings. Thanks

**Pull request merged**
